[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
